search:
    lang: ja
    locale: ja
    result_type: recent
    count:
    until:
    search_count: 3
    # query = XXXXXXXXXX
    # geocode = XXXXXXXXXX
    # since_id = XXXXXXXXXX
    # max_id = XXXXXXXXXX
    # include_entities = XXXXXXXXX

########################################
#[tokens]:Twitter公式で取得したアクセスキー等

#query:検索単語
#geocode:位置の範囲
#lang:検索の対象となる地域の言語コード
#local:検索クエリの言語コード
#result_type:取得するツイートの種類
#count:1回のアクセスにおける取得件数
#until:指定日より以前のツイートを取得
#since_id:これより未来のツイートを取得
#max_id:これより過去のツイートを取得
#include_entities:ツイートオブジェクト内のentitiesプロパティを含めるか否か
#search_count:アクセス回数（0:無限）

#Tweet_save_dir_path:保存先
########################################
